### ISSUE TITLE
Handle `pg_dump` / `pg_restore` workflow when TLE extensions are installed

### ISSUE THREAD

**Issue by jkatz** [aws/pg_tle#44]
Currently, a `pg_dump` file will not put out TLE artifacts in the correct install order. For example, if we have a TLE extensions called "tle_test", `pg_dump` will generate something like this:

```
CREATE EXTENSION pg_tle;
CREATE EXTESNION tle_test;

CREATE FUNCTION pgtle."tle_test.control()" ...
```

This will fail, as the "control file" is not available yet in the DB.

One option is to provide a `pg_tle_dump` wrapper script around `pg_dump` to put the TLE artifacts in the correct order.

**Comment by formalLogicGirl** [comment]
In general, pg_dump creates extension objects before function/procedure objects, which is why we have this behavior.

I have a viable path for fixing this. I did a prototype implementation to confirm that adding an entry to pg_depend for the .control file in tleCreateExtension() makes pg_dump do the correct ordering, with the creation of the extension file after the function it depends on. pg_dump output from my implementation looks like the following, note that function test123.control will be created before extension test123.

` --
-- PostgreSQL database dump
---- Dumped from database version 14.6
-- Dumped by pg_dump version 14.6SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;--
-- Name: pgtle; Type: SCHEMA; Schema: -; Owner: swmiller
--CREATE SCHEMA pgtle;
ALTER SCHEMA pgtle OWNER TO swmiller;--
-- Name: pg_tle; Type: EXTENSION; Schema: -; Owner: -
--CREATE EXTENSION IF NOT EXISTS pg_tle WITH SCHEMA pgtle;
--
-- Name: EXTENSION pg_tle; Type: COMMENT; Schema: -; Owner:
--COMMENT ON EXTENSION pg_tle IS 'Trusted Language Extensions for PostgreSQL';
--
-- Name: test123.control(); Type: FUNCTION; Schema: pgtle; Owner: swmiller
--
CREATE FUNCTION pgtle."test123.control"() RETURNS text
    LANGUAGE sql
    AS $_X$SELECT $_pgtle_i_$default_version = '1.1'
comment = 'Test TLE Functions'
relocatable = false
superuser = false
trusted = false
requires = 'pg_tle'
$_pgtle_i_$$_X$;
ALTER FUNCTION pgtle."test123.control"() OWNER TO swmiller;--
-- Name: test123; Type: EXTENSION; Schema: -; Owner: -
--CREATE EXTENSION IF NOT EXISTS test123 WITH SCHEMA public;
--
-- Name: EXTENSION test123; Type: COMMENT; Schema: -; Owner:
--COMMENT ON EXTENSION test123 IS 'Test TLE Functions'; 
`

I will proceed with a pull request for a fix along this approach.
